name: hyunamy
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "pyproject.toml"

jobs:
  publish-node:
    name: hyunamy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: hyunamy
        if: github.event.repository.fork == false
        uses: Comfy-Org/publish-node-action@main
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
        continue-on-error: true
      - name: Print error message if Publish Custom Node fails
        if: failure()
        run: echo "Publishing failed. Please check the logs for more details."
